CREATE TABLE stock_equity_data(
  serial_num serial NOT NULL,
  trade_date date NOT NULL,
  sc_code  integer NOT NULL,
  sc_name character varying(50) NOT NULL,
  sc_group character varying(50),
  sc_type character varying(50),
  open_price double precision,
  high_price double precision,
  low_price double precision,
  close_price double precision,
  last_price double precision,
  prevclose double precision,
  no_of_trades double precision,
  no_of_shares double precision,
  net_turn_over double precision,
  PRIMARY KEY(trade_date,sc_code))	